### ISSUE TITLE
Why does base.js need to load learn.json? (and where is it?)

### ISSUE THREAD

**Issue by nelsonic** [tastejs/todomvc-common#14]
Hi! we are trying to build a TodoMVC Example for the _latest_ version of Riot.js
But when we try to load `todomvc-common/base.js` in our `index.html` we see the following error (in Chrome Dev Tools / Console):

<img width="523" alt="base js-needs-learn json-todomvc-common" src="https://cloud.githubusercontent.com/assets/194400/8716950/2ea1ad96-2b8e-11e5-8651-068ddf81d0e1.png">

![base js-line-248-needs-learn json-why](https://cloud.githubusercontent.com/assets/194400/8716992/a5198ae8-2b8e-11e5-8c59-9daa9bdd9d27.png)

This line: https://github.com/tastejs/todomvc-common/blob/e82d0c79e01687ce7407df786cc784ad82166cb3/base.js#L248

What is `learn.json` and where can we source it from to prevent this 404?
_Thanks_!

**Comment by kn9ts** [comment]
Is base.js even useful at all?

**Comment by mriccia** [comment]
Just looked through the todomvc main repo and I can see that learn.json is at the root of the repository:
https://github.com/tastejs/todomvc/blob/master/learn.json
base.js is used render the information on the left (highlighted in the screenshot below)
<img width="1039" alt="untitled" src="https://cloud.githubusercontent.com/assets/5655093/11518372/88a32178-9888-11e5-9480-d9e5d7e40b15.png">

**Comment by kn9ts** [comment]
@mriccia OK. So it is actaully irrelevant when you're trying out todomvc in your machine :)

**Comment by mriccia** [comment]
@kn9ts lol yes that's correct, so everything will still work if you don't include base.js
